### ISSUE TITLE
SemanticLogger integration not correlating logs with server/environment

### ISSUE THREAD

**Issue by Drowze** [DataDog/dd-trace-rb#2356]
**Current behaviour**
SemanticLogger integration is not correlating logs with server/environment (configured via DD_SERVER/DD_ENV)

**Expected behaviour**
Given the quote below, I'd expect `rails_semantic_logger` to _just work_ with Datadog and correlate the logs with their traces and correct env/service.
> For Rails applications using the default logger (ActiveSupport::TaggedLogging), lograge, or semantic_logger, trace correlation injection is automatically configured.
_from: https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/ruby/_

**Steps to reproduce**
- Started a Datadog docker agent using docker-compose:
   ```yaml
   dd-agent:
     image: gcr.io/datadoghq/agent:7
     pid: host
     environment:
       - DD_ENV=rafael-testing
       - DD_API_KEY=${DD_API_KEY}
       - DD_LOGS_ENABLED=true
     ports:
      - 8126:8126
      - 10518:10518
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /var/lib/docker/containers:/var/lib/docker/containers:ro
       - ${PWD}/dd-agent/logs.yaml:/conf.d/logs.yaml
   ```
- My mounted logs configuration:
   ```yaml
   logs:
     - type: tcp
       port: 10518
       service: log-echo
       source: ruby
   ```
- On a Rails server (**on the host machine, not a container**) I added the gems `rails_semantic_logger` and `net_tcp_client`
- On datadog configuration I added:
    ```ruby
    c.tracing.instrument :rails
    c.tracing.log_injection = true
    ```
- On `config/development.rb` I got:
    ```ruby
    config.log_level = ENV.fetch("LOG_LEVEL", "info").downcase.strip.to_sym
    config.rails_semantic_logger.add_file_appender = false
    config.semantic_logger.add_appender(appender: :tcp, server: "localhost:10518")
    ```
- On a Rails route, I just added a simple `Rails.logger.info("Hello world")`
- Finally, I started the Rails server with:
  ```
  DD_SERVICE=auth-user DD_VERSION=after-sl DD_ENV=rafael-testing2 bundle exec rails server
  ```
- Result:
  ![image](https://user-images.githubusercontent.com/9031589/200634197-6a820e96-4367-45cb-afee-26cf7db1aa9d.png)

**Environment**

* **ddtrace version:** 1.5.1
* **Ruby version:** 
* **Operating system:** 3.1.2
* **Relevant library versions:** net_tcp_client (2.2.0), rails_semantic_logger (4.10.0), semantic_logger (4.12.0)

**Comment by Drowze** [comment]
Some further testing, this time NOT using any Ruby process. With only a datadog agent with the following logs config:
```yaml
logs:
  - type: tcp
    port: 10518
    service: log-echo
    source: ruby
```

1. A JSON log with `dd` on the root object.
    ```bash
    echo '{
      "dd": {
        "trace_id": "754516775358317257",
        "env": "rafael-testing",
        "service": "auth-user",
        "version":42
      },
      "ddsource": "ruby-overwrite",
      "message": "HI DAWG"
    }' | jq -c | nc localhost 10518
    ```
    trace reported ✅
    environment reported ✅
    service reported (overwritten) ✅
    version reported ✅
    source: ignored (not overwritten) :x:

2. A JSON log with `dd` inside a `named_tags` object (this is how SemanticLogger does it by default)
    ```bash
    echo '{
      "named_tags": {
        "dd": {
          "trace_id": "754516775358317257",
          "env": "rafael-testing",
          "service": "auth-user",
          "version":42
        },
        "ddsource": "ruby-overwrite"
      },
      "message": "HI DAWG"
    }' | jq -c | nc localhost 10518
    ```
    trace reported ✅
    environment ignored :x:
    service ignored(not overwritten) :x:
    version ignored :x:
    source ignored (not overwritten) :x:

3. A formatted plain string
    ```
    echo '[dd.env=rafael-testing dd.service=auth-user dd.version=42 dd.source=ruby-overwrite dd.trace_id=754516775358317257] HI DAWG' | nc localhost 10518
    ```
    trace reported ✅
    environment reported ✅
    service reported (overwritten) ✅
    version reported ✅
    source: ignored (not overwritten) :x:
